export const projects = [
  {
    title: "Physiotherapy Studio Information System",
    description:
      "A robust web application designed for the management of a physiotherapy studio. It includes functionalities for managing reservations, clients, services, and a blog. The dashboard also provides charts for decision-making, with Google Maps and reservation filtering for the public section.",
    technologies: {
      backend: [
        { name: "C#" },
        { name: "ASP.NET Core", icon: "SiDotnet" },
        {
          name: "Entity Framework Core",
        },
        { name: "MSSQL", icon: "DiMsqlServer" },
        { name: "JWT" },
        { name: "REST API" },
        { name: "Monolithic Architecture" },
      ],
      frontend: [
        { name: "Next.js", icon: "SiNextdotjs" },
        { name: "React", icon: "FaReact" },
        { name: "Tailwind CSS", icon: "SiTailwindcss" },
        { name: "TypeScript", icon: "SiTypescript" },
      ],
      deployment: [
        { name: "Vercel", icon: "SiVercel" },
        { name: "Microsoft Azure", icon: "SiMicrosoftazure" },
      ],
    },
    duration: "2023-2024",
    icon: "FaLaptopCode",
    image: "/projects/dp.png",
    sourceCode: {
      backend: "https://github.com/MarekSutora/physio-backend",
      frontend: "https://github.com/MarekSutora/physio-frontend",
    },
    liveDemo: "https://physio-studio-website.vercel.app/",
  },
  {
    title: "Movie Search Web Application",
    description:
      "A movie database application where users can search for movies, view details, and manage a list of favorites. It integrates with the OMDB API and features infinite scrolling, responsive design, and local storage for favorite movie management.",
    technologies: {
      frontend: [
        { name: "React", icon: "FaReact" },
        { name: "TypeScript", icon: "SiTypescript" },
        { name: "Chakra UI", icon: "SiChakraui" },
        { name: "SCSS", icon: "FaSass" },
        { name: "React Query" },
        { name: "Vite", icon: "SiVite" },
      ],
      deployment: [{ name: "Vercel", icon: "SiVercel" }],
    },
    duration: "2024",
    icon: "FaFilm",
    image: "/projects/mvdb.png",
    sourceCode: "https://github.com/MarekSutora/movie-database",
    liveDemo: "https://movie-database-roan.vercel.app",
  },
  {
    title: "Portfolio Website",
    description:
      "A personal portfolio website showcasing my projects, skills, and experience. It features a dark theme, animations, and a responsive design.",
    technologies: {
      all: [
        { name: "Next.js", icon: "SiNextdotjs" },
        { name: "React", icon: "FaReact" },
        { name: "TypeScript", icon: "SiTypescript" },
        { name: "Tailwind CSS", icon: "SiTailwindcss" },
      ],
    },
    duration: "2024",
    icon: "FaUser",
    image: "/projects/prtfl.png",
    sourceCode: "https://github.com/MarekSutora/MarekSutoraSK",
    liveDemo: "https://www.mareksutora.sk",
  },
];

export const education = [
  {
    university: "University of Žilina",
    faculty: "Faculty of Management Science and Informatics",
    duration: "2018 - 2021",
    degree: "Bachelor's degree in Informatics",
    description:
      "The Bachelor's degree in Informatics equipped me with a strong foundation in computer science. Throughout my studies, I gained hands-on experience in object-oriented programming, databases, web development and much more. This period allowed me to build several projects that strengthened my problem-solving and coding abilities across various technologies.",
    technologies: [
      { name: "C/C++" },
      { name: "Java", icon: "FaJava" },
      { name: "Oracle SQL", icon: "SiOracle" },
      { name: "JavaScript", icon: "FaJsSquare" },
      { name: "HTML", icon: "FaHtml5" },
      { name: "CSS", icon: "FaCss3" },
      { name: "PHP", icon: "FaPhp" },
      { name: "R" },
      { name: "Enterprise Architect" },
      { name: "UML" },
      { name: "Assembly" },
      { name: "Microsoft Excel :)", icon: "SiMicrosoftexcel" },
      { name: "Matlab" },
    ],
    fields: [
      { name: "Web Development" },
      { name: "Algorithms" },
      { name: "Data Structures" },
      { name: "Databases" },
      { name: "Graph Theory" },
      { name: "Modeling and Simulation" },
      { name: "Operating Systems" },
      { name: "Computer Networks" },
      { name: "Discrete Mathematics" },
      { name: "Probability and Statistics" },
      { name: "Economics" },
      { name: "Software Modeling" },
      { name: "Linear Algebra" },
      { name: "Mathematical Analysis" },
      { name: "Object-Oriented Programming" },
      { name: "Data Science" },
    ],
  },
  {
    university: "University of Žilina",
    faculty: "Faculty of Management Science and Informatics",
    duration: "2021 - 2023",
    degree: "Master's degree in Biomedical Informatics",
    description:
      "The Master's program in Biomedical Informatics allowed me to specialize in medical data analysis, machine learning, and development of healthcare applications. I also worked on a research project focused on microfluidics simulations.",
    technologies: [
      { name: "Python", icon: "FaPython" },
      { name: "R" },
      { name: "Oracle SQL", icon: "SiOracle" },
      { name: "Matlab" },
      { name: "React", icon: "FaReact" },
      { name: "JavaScript", icon: "FaJsSquare" },
      { name: "Node.js", icon: "FaNodeJs" },
      { name: "Express.js" },
      { name: "Microsoft Excel :)", icon: "SiMicrosoftexcel" },
    ],
    fields: [
      { name: "Data Mining" },
      { name: "Machine Learning" },
      { name: "Bioinformatics" },
      { name: "Microfluidics Simulations" },
      { name: "Modeling and Simulation" },
      { name: "Image Processing" },
      { name: "Medical Informatics" },
      { name: "Healthcare Systems" },
      { name: "Reliability Engineering" },
      { name: "Cryptography" },
      { name: "Infomation Theory" },
      { name: "Fuzzy Logic" },
      { name: "Biology and Chemistry for Informatics" },
    ],
  },
];

export const experience = [
  {
    position: "Backend Developer",
    company: "Codium",
    workType: "Full-time",
    duration: "September 2024 - Present",
    description:
      "I am working mainly on backend solutions designed to handle streams of data from betting providers, forming the backbone of the Doxxbet platform. This data stream provides all the necessary information for customers to be able to place bets. In addition to backend development, I also sometimes work on a backoffice web application that supports internal operations. The system is built using a microservices architecture with Kafka for data streaming, .NET Core and .NET Framework for backend development, and MSSQL for data storage. We use Dapper for database interactions, and our workflows are managed with TeamCity and GitLab for CI/CD. We also monitor and troubleshoot data pipelines with Elasticsearch, Kibana, and Redis.",
    technologies: [
      { name: "C#", icon: "SiCsharp" },
      { name: ".NET Core", icon: "SiDotnet" },
      { name: ".NET Framework", icon: "SiDotnet" },
      { name: "Kafka", icon: "SiApachekafka" },
      { name: "jQuery", icon: "SiJquery" },
      { name: "MSSQL", icon: "DiMsqlServer" },
      { name: "Dapper" },
      { name: "TeamCity", icon: "SiJetbrains" },
      { name: "GitLab", icon: "SiGitlab" },
      { name: "Elasticsearch", icon: "SiElasticsearch" },
      { name: "Kibana", icon: "SiKibana" },
      { name: "Redis", icon: "SiRedis" },
    ],
  },
  {
    position: "Fullstack Developer",
    company: "Descartes",
    workType: "Internship",
    duration: "July 2022 - June 2024",
    description:
      "I Worked on a telematics project, where I was mainly responsible for displaying real-time processed data on charts and interactive maps with markers and animations. Collaborated with a team of 8-11 members in an Agile environment with daily stand-ups and sprint planning, using Azure DevOps for project management.",
    technologies: [
      { name: "C#", icon: "SiCsharp" },
      { name: "ASP.NET Core MVC", icon: "SiDotnet" },
      { name: "Microservices" },
      { name: "REST API" },
      { name: "Dapper" },
      { name: "MSSQL", icon: "DiMsqlServer" },
      { name: "JavaScript", icon: "FaJs" },
      { name: "HTML", icon: "FaHtml5" },
      { name: "CSS", icon: "FaCss3" },
      { name: "MapLibre" },
      { name: "Azure DevOps", icon: "SiAzuredevops" },
      { name: "Agile", icon: "FaBalanceScale" },
      { name: "Scrum", icon: "FaTasks" },
    ],
  },
];
