export const projectsEn = [
  {
    title: "Physiotherapy Studio Information System",
    description:
      "A robust web application designed for the presentation and management of a physiotherapy studio. It includes functionalities for managing reservations, clients, services, running a blog and providing statistics through charts.",
    technologies: {
      backend: [
        { name: "C#" },
        { name: "ASP.NET Core", icon: "SiDotnet" },
        {
          name: "Entity Framework Core",
        },
        { name: "MSSQL", icon: "DiMsqlServer" },
        { name: "JWT" },
        { name: "REST API" },
        { name: "Monolithic Architecture" },
      ],
      frontend: [
        { name: "Next.js", icon: "SiNextdotjs" },
        { name: "React", icon: "FaReact" },
        { name: "Tailwind CSS", icon: "SiTailwindcss" },
        { name: "TypeScript", icon: "SiTypescript" },
        { name: "Google Maps API", icon: "SiGooglemaps" },
        { name: "PrimeReact" },
        { name: "shadcn/ui" },
      ],
      deployment: [
        { name: "Vercel", icon: "SiVercel" },
        { name: "Microsoft Azure", icon: "SiMicrosoftazure" },
      ],
    },
    duration: "2023-2024",
    icon: "FaLaptopCode",
    image: "/projects/dp.png",
    sourceCode: {
      backend: "https://github.com/MarekSutora/physio-backend",
      frontend: "https://github.com/MarekSutora/physio-frontend",
    },
    liveDemo: "https://physio-studio-website.vercel.app/",
  },
  {
    title: "Movie Search Web Application",
    description:
      "A movie database application where users can search for movies, view details, and manage a list of favorites. It integrates with the OMDB API and features infinite scrolling, responsive design, and local storage for favorite movie management.",
    technologies: {
      frontend: [
        { name: "React", icon: "FaReact" },
        { name: "TypeScript", icon: "SiTypescript" },
        { name: "Chakra UI", icon: "SiChakraui" },
        { name: "SCSS", icon: "FaSass" },
        { name: "React Query" },
        { name: "Vite", icon: "SiVite" },
      ],
      deployment: [{ name: "Vercel", icon: "SiVercel" }],
    },
    duration: "2024",
    icon: "FaFilm",
    image: "/projects/mvdb.png",
    sourceCode: "https://github.com/MarekSutora/movie-database",
    liveDemo: "https://movie-database-roan.vercel.app",
  },
  {
    title: "Portfolio Website",
    description:
      "A personal portfolio website showcasing my projects, skills, and experience. It features a dark theme, animations, and a responsive design.",
    technologies: {
      all: [
        { name: "Next.js", icon: "SiNextdotjs" },
        { name: "React", icon: "FaReact" },
        { name: "TypeScript", icon: "SiTypescript" },
        { name: "Tailwind CSS", icon: "SiTailwindcss" },
      ],
    },
    duration: "2024",
    icon: "FaUser",
    image: "/projects/prtfl.png",
    sourceCode: "https://github.com/MarekSutora/MarekSutoraSK",
    liveDemo: "https://www.mareksutora.sk",
  },
];

export const projectsSk = [
  {
    title: "Informačný systém pre Fyzioterapeutické štúdio",
    description:
      "Robustná responzívna webová aplikácia určená na prezentáciu a manažovanie fyzioterapeutického štúdia. Obsahuje funkcionalitu na manažovanie rezervácií, klientov, služieb, prevádzkovanie blogu a poskytovanie štatistík pomocou grafov.",
    technologies: {
      backend: [
        { name: "C#" },
        { name: "ASP.NET Core", icon: "SiDotnet" },
        { name: "Entity Framework Core" },
        { name: "MSSQL", icon: "DiMsqlServer" },
        { name: "JWT" },
        { name: "REST API" },
        { name: "Monolitická architektúra" },
      ],
      frontend: [
        { name: "Next.js", icon: "SiNextdotjs" },
        { name: "React", icon: "FaReact" },
        { name: "Tailwind CSS", icon: "SiTailwindcss" },
        { name: "TypeScript", icon: "SiTypescript" },
        { name: "Google Maps API", icon: "SiGooglemaps" },
        { name: "PrimeReact" },
        { name: "shadcn/ui" },
      ],
      deployment: [
        { name: "Vercel", icon: "SiVercel" },
        { name: "Microsoft Azure", icon: "SiMicrosoftazure" },
      ],
    },
    duration: "2023-2024",
    icon: "FaLaptopCode",
    image: "/projects/dp.png",
    sourceCode: {
      backend: "https://github.com/MarekSutora/physio-backend",
      frontend: "https://github.com/MarekSutora/physio-frontend",
    },
    liveDemo: "https://physio-studio-website.vercel.app/",
  },
  {
    title: "Webová aplikácia na vyhľadávanie filmov",
    description:
      "Aplikácia filmovej databázy, kde používatelia môžu vyhľadávať filmy, zobraziť detaily a spravovať zoznam obľúbených. Integruje sa s OMDB API a ponúka nekonečné scrollovanie, responzívny dizajn a ukladanie obľúbených filmov v lokálnom úložisku.",
    technologies: {
      frontend: [
        { name: "React", icon: "FaReact" },
        { name: "TypeScript", icon: "SiTypescript" },
        { name: "Chakra UI", icon: "SiChakraui" },
        { name: "SCSS", icon: "FaSass" },
        { name: "React Query" },
        { name: "Vite", icon: "SiVite" },
      ],
      deployment: [{ name: "Vercel", icon: "SiVercel" }],
    },
    duration: "2024",
    icon: "FaFilm",
    image: "/projects/mvdb.png",
    sourceCode: "https://github.com/MarekSutora/movie-database",
    liveDemo: "https://movie-database-roan.vercel.app",
  },
  {
    title: "Portfólio webstránka",
    description:
      "Osobná portfólio webstránka prezentujúca moje projekty, zručnosti a skúsenosti. Obsahuje tmavý režim, animácie a responzívny dizajn.",
    technologies: {
      all: [
        { name: "Next.js", icon: "SiNextdotjs" },
        { name: "React", icon: "FaReact" },
        { name: "TypeScript", icon: "SiTypescript" },
        { name: "Tailwind CSS", icon: "SiTailwindcss" },
      ],
    },
    duration: "2024",
    icon: "FaUser",
    image: "/projects/prtfl.png",
    sourceCode: "https://github.com/MarekSutora/MarekSutoraSK",
    liveDemo: "https://www.mareksutora.sk",
  },
];

export const educationEn = [
  {
    university: "University of Žilina",
    faculty: "Faculty of Management Science and Informatics",
    duration: "2021 - 2023",
    degree: "Master's degree in Biomedical Informatics",
    description:
      "The Master's program in Biomedical Informatics allowed me to specialize in medical data analysis, machine learning, and development of healthcare applications. I also worked on a research project focused on microfluidics simulations.",
    technologies: [
      { name: "Python", icon: "FaPython" },
      { name: "R" },
      { name: "Oracle SQL", icon: "SiOracle" },
      { name: "Matlab" },
      { name: "React", icon: "FaReact" },
      { name: "JavaScript", icon: "FaJsSquare" },
      { name: "Node.js", icon: "FaNodeJs" },
      { name: "Express.js" },
      { name: "Microsoft Excel :)", icon: "SiMicrosoftexcel" },
    ],
    fields: [
      { name: "Data Mining" },
      { name: "Machine Learning" },
      { name: "Bioinformatics" },
      { name: "Microfluidics Simulations" },
      { name: "Modeling and Simulation" },
      { name: "Image Processing" },
      { name: "Medical Informatics" },
      { name: "Reliability Engineering" },
      { name: "Cryptography" },
      { name: "Infomation Theory" },
      { name: "Fuzzy Logic" },
      { name: "Biology and Chemistry for Informatics" },
    ],
  },
  {
    university: "University of Žilina",
    faculty: "Faculty of Management Science and Informatics",
    duration: "2018 - 2021",
    degree: "Bachelor's degree in Informatics",
    description:
      "The Bachelor's degree in Informatics equipped me with a strong foundation in computer science. Throughout my studies, I gained hands-on experience in object-oriented programming, databases, web development and much more. This period allowed me to build several projects that strengthened my problem-solving and coding abilities across various technologies.",
    technologies: [
      { name: "C/C++" },
      { name: "Java", icon: "FaJava" },
      { name: "Oracle SQL", icon: "SiOracle" },
      { name: "JavaScript", icon: "FaJsSquare" },
      { name: "HTML", icon: "FaHtml5" },
      { name: "CSS", icon: "FaCss3" },
      { name: "PHP", icon: "FaPhp" },
      { name: "R" },
      { name: "Enterprise Architect" },
      { name: "UML" },
      { name: "Assembly" },
      { name: "Microsoft Excel :)", icon: "SiMicrosoftexcel" },
      { name: "Matlab" },
    ],
    fields: [
      { name: "Web Development" },
      { name: "Algorithms" },
      { name: "Data Structures" },
      { name: "Databases" },
      { name: "Graph Theory" },
      { name: "Modeling and Simulation" },
      { name: "Operating Systems" },
      { name: "Computer Networks" },
      { name: "Discrete Mathematics" },
      { name: "Probability and Statistics" },
      { name: "Economics" },
      { name: "Software Modeling" },
      { name: "Linear Algebra" },
      { name: "Mathematical Analysis" },
      { name: "Object-Oriented Programming" },
      { name: "Data Science" },
    ],
  },
];

export const educationSk = [
  {
    university: "Žilinská univerzita v Žiline",
    faculty: "Fakulta riadenia a informatiky",
    duration: "2021 - 2023",
    degree: "Inžiniersky titul v odbore Biomedicínska informatika",
    description:
      "Inžiniersky program Biomedicínska informatika mi umožnil špecializovať sa na analýzu medicínskych dát, strojové učenie a vývoj aplikácií pre zdravotníctvo. Taktiež som pracoval na výskumnom projekte zameranom na simulácie mikrofluidiky.",
    technologies: [
      { name: "Python", icon: "FaPython" },
      { name: "R" },
      { name: "Oracle SQL", icon: "SiOracle" },
      { name: "Matlab" },
      { name: "React", icon: "FaReact" },
      { name: "JavaScript", icon: "FaJsSquare" },
      { name: "Node.js", icon: "FaNodeJs" },
      { name: "Express.js" },
      { name: "Microsoft Excel :)", icon: "SiMicrosoftexcel" },
    ],
    fields: [
      { name: "Data mining" },
      { name: "Strojové učenie" },
      { name: "Bioinformatika" },
      { name: "Simulácie mikrofluidiky" },
      { name: "Modelovanie a simulácia" },
      { name: "Spracovanie obrazu" },
      { name: "Medicínska informatika" },
      { name: "Teória spoľahlivosti" },
      { name: "Kryptografia" },
      { name: "Teória informácií" },
      { name: "Fuzzy logika" },
      { name: "Biológia a chémia pre informatiku" },
    ],
  },
  {
    university: "Žilinská univerzita v Žiline",
    faculty: "Fakulta riadenia a informatiky",
    duration: "2018 - 2021",
    degree: "Bakalársky titul v odbore Informatika",
    description:
      "Bakalárske štúdium Informatiky mi poskytlo silný základ v oblasti informatiky. Počas štúdia som získal praktické skúsenosti s objektovo orientovaným programovaním, databázami, webovým vývojom a mnohým ďalším. Toto obdobie mi umožnilo vytvoriť niekoľko projektov, ktoré posilnili moje schopnosti riešiť problémy a využívať v rôzne technológie.",
    technologies: [
      { name: "C/C++" },
      { name: "Java", icon: "FaJava" },
      { name: "Oracle SQL", icon: "SiOracle" },
      { name: "JavaScript", icon: "FaJsSquare" },
      { name: "HTML", icon: "FaHtml5" },
      { name: "CSS", icon: "FaCss3" },
      { name: "PHP", icon: "FaPhp" },
      { name: "R" },
      { name: "Enterprise Architect" },
      { name: "UML" },
      { name: "Assembler" },
      { name: "Microsoft Excel :)", icon: "SiMicrosoftexcel" },
      { name: "Matlab" },
    ],
    fields: [
      { name: "Web development" },
      { name: "Algoritmy" },
      { name: "Dátové štruktúry" },
      { name: "Databázy" },
      { name: "Teória grafov" },
      { name: "Modelovanie a simulácia" },
      { name: "Operačné systémy" },
      { name: "Počítačové siete" },
      { name: "Diskrétna matematika" },
      { name: "Pravdepodobnosť a štatistika" },
      { name: "Ekonomika" },
      { name: "Softvérové modelovanie" },
      { name: "Lineárna algebra" },
      { name: "Matematická analýza" },
      { name: "Objektovo orientované programovanie" },
      { name: "Data Science" },
    ],
  },
];

export const experienceEn = [
  // {
  //   position: "Backend Developer",
  //   company: "Codium",
  //   workType: "Full-time",
  //   duration: "September 2024 - Present",
  //   description:
  //     "I am working mainly on backend solutions designed to handle streams of data from betting providers, forming the backbone of the Doxxbet platform. This data stream provides all the necessary information for customers to be able to place bets. In addition to backend development, I also sometimes work on a backoffice web application that supports internal operations.",
  //   technologies: [
  //     { name: "Microservices" },
  //     { name: "C#", icon: "SiCsharp" },
  //     { name: ".NET Core", icon: "SiDotnet" },
  //     { name: ".NET Framework", icon: "SiDotnet" },
  //     { name: "Kafka", icon: "SiApachekafka" },
  //     { name: "jQuery", icon: "SiJquery" },
  //     { name: "MSSQL", icon: "DiMsqlServer" },
  //     { name: "Dapper" },
  //     { name: "TeamCity", icon: "SiJetbrains" },
  //     { name: "GitLab", icon: "SiGitlab" },
  //     { name: "Elasticsearch", icon: "SiElasticsearch" },
  //     { name: "Kibana", icon: "SiKibana" },
  //     { name: "Redis", icon: "SiRedis" },
  //   ],
  // },
  {
    position: "Fullstack Developer",
    company: "Descartes",
    workType: "Internship",
    duration: "July 2022 - June 2024",
    description:
      "I Worked on a telematics project, where I was mainly responsible for displaying real-time processed data on charts and interactive maps with markers and animations. Collaborated with a team of 8-11 members in an Agile environment with daily stand-ups and sprint planning, using Azure DevOps for project management.",
    technologies: [
      { name: "Microservices" },
      { name: "C#", icon: "SiCsharp" },
      { name: "ASP.NET Core MVC", icon: "SiDotnet" },
      { name: "REST API" },
      { name: "Dapper" },
      { name: "MSSQL", icon: "DiMsqlServer" },
      { name: "JavaScript", icon: "FaJs" },
      { name: "HTML", icon: "FaHtml5" },
      { name: "CSS", icon: "FaCss3" },
      { name: "MapLibre" },
      { name: "Azure DevOps", icon: "SiAzuredevops" },
      { name: "Agile", icon: "FaBalanceScale" },
      { name: "Scrum", icon: "FaTasks" },
    ],
  },
];

export const experienceSk = [
  {
    position: "Fullstack Developer",
    company: "Descartes",
    workType: "Stáž",
    duration: "Júl 2022 - Jún 2024",
    description:
      "Pracoval som na projekte telematiky, kde som bol hlavne zodpovedný za zobrazovanie spracovaných dát v reálnom čase na grafoch a interaktívnych mapách s markermi a animáciami. Spolupracoval som s tímom 8-11 členov v Agile prostredí s dennými stand-upmi a plánovaním sprintov, pričom sme na riadenie projektov používali Azure DevOps.",
    technologies: [
      { name: "Mikroslužby" },
      { name: "C#", icon: "SiCsharp" },
      { name: "ASP.NET Core MVC", icon: "SiDotnet" },
      { name: "REST API" },
      { name: "Dapper" },
      { name: "MSSQL", icon: "DiMsqlServer" },
      { name: "JavaScript", icon: "FaJs" },
      { name: "HTML", icon: "FaHtml5" },
      { name: "CSS", icon: "FaCss3" },
      { name: "MapLibre" },
      { name: "Azure DevOps", icon: "SiAzuredevops" },
      { name: "Agile", icon: "FaBalanceScale" },
      { name: "Scrum", icon: "FaTasks" },
    ],
  },
];
