import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Background from "@/components/Background";
import Providers from "./Providers";
import CustomCursor from "@/components/CustomCursor";
import FluidDistortion from "@/components/Fluid/FluidDistortion";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className="m-0 p-0 overflow-x-hidden w-full h-full relative"
    >
      <body className={cn(inter, "m-0 p-0 overflow-x-hidden w-full h-full")}>
        <Providers>
          <CustomCursor />
          <div className="w-full h-full z-50">
            <Background />
            {children}
          </div>
        </Providers>
        <FluidDistortion />
      </body>
    </html>
  );
}
